Edumia_v2/Edumia_v2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.urls import path,include
from rest_framework import routers
from api.urls import router
from django.conf.urls import url
from api.urls import router
from django.conf.urls import url
urlpatterns = [
    path('', TemplateView.as_view(template_name='users/dashboard.html'), name='dashboard'),
    path('admin/', admin.site.urls),
    path('students/',include('students.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('staff/',include('Staff.urls')),
    path('klass/',include('klass.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/v1/',include('api.urls')),
]

Edumia_v2/api/urls.py
from rest_framework import routers
from .views import *
from django.urls import path,include
from api import views



#api
router = routers.DefaultRouter()
router.register(r'category_list',StudentCategoryViewSet)
router.register(r'studentsprofile',StudentProfile,basename='studentsprofile')
#router.register(r'klass_students',KlassStudentList,basename='klass_students')
#staff module
router.register(r'staffprofile',StaffProfileViewSet,basename='staffprofile')

urlpatterns = [
    path('klass_students',views.KlassStudentList.as_view()),
    path('search',views.SearchStudent.as_view()),
    path('staffsearch',views.SearchStaff.as_view()),

    ]+router.urls

Edumia_v2/students/urls.py
from django.urls import path,include
from students import views


urlpatterns = [path('pending',views.pending,name="pending"),
               path('status_approval',views.status_approvel,name="approvel"),
               path('status_denial',views.status_denial,name="denial"),
               path('',views.studentdashboard,name="studentdashboard"),
               path('add-student/', views.AddStudent, name='add-student'),
               path('reverse',views.success,name="success"),
               path('ajax/get_divisions/', views.get_divisions, name='ajax_get_divisions'),
               path('all_students',views.all_students,name = 'all_students'),
               path('profile',views.profile,name='profile'),
               path('student_phone_numbers',views.student_phone_numbers,name='student_phone_numbers'),
               path('contact_numbers',views.contact_numbers,name='contact_numbers'),
               path('student_info',views.student_info,name='student_info'),

               ]

Edumia_v2/students/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from django.conf import settings
from klass.models import Klass,Division
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone


# Create your models here.
class StudentsProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    admission_number = models.IntegerField(null=False, unique=True)
    admission_date = models.DateField()
    status_choice = (("0", "Pending"),
                     ("1", "Approve"),
                     ("2", "Deny"))
    status = models.CharField(max_length=1, default=0, choices=status_choice)
    klass = models.ForeignKey('klass.Klass', on_delete=models.CASCADE)
    division = models.ForeignKey("klass.Division", on_delete=models.CASCADE)

    # Personnel Details
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=100,
                                  help_text="Enter First Name")
    last_name = models.CharField(max_length=100,
                                 help_text="Enter Last Name")
    birthday = models.DateField()

    gender_choice = (("M", "Male"),
                     ("F", "Female"),
                     ("O", "Other"))
    gender = models.CharField(max_length=1, choices=gender_choice)
    birth_place = models.CharField(max_length=100, null=True, blank=True)
    nationality = CountryField()
    mothertounge = models.CharField(max_length=100, null=True, blank=True)
    category = models.ForeignKey("StudentCategory", on_delete=models.CASCADE)

    religion = models.CharField(max_length=100, null=True, blank=True)
    caste = models.CharField(max_length=100, null=True, blank=True)
    caste_category = models.CharField(max_length=100, null=True, blank=True)

    # Contact Details

    address_line1 = models.CharField(max_length=250)
    address_line2 = models.CharField(max_length=250)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    pin_code = models.CharField(max_length=100)
    country = CountryField()
    father_name = models.CharField(max_length=100)
    phone_number = PhoneNumberField()
    mother_name = models.CharField(max_length=100, null=True, blank=True)
    mother_phone_number = PhoneNumberField()
    aadhaar_Number = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=254, null=True, blank=True)

    # Health Report

    height = models.CharField(max_length=100, null=True, blank=True)
    weight = models.CharField(max_length=100, null=True, blank=True)
    blood_choice = (("A+", "A Positive"),
                    ("A-", "A Negative"),
                    ("B+", "B Positive"),
                    ("B-", "B Negative"),
                    ("O+", "O Positive"),
                    ("O-", "O Negative"),
                    ("AB+", "AB Positive"),
                    ("AB-", "AB Negative"))
    blood_group = models.CharField(max_length=3, choices=blood_choice)
    vaccination_details = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.first_name

    def session_data(self):
        session = {
            'admission_date': self.admission_date,
            'klass': self.klass,
            'category': self.category,
            'phone_number': self.phone_number
        }
        return session
    def get_absolute_url(self):
        return reverse('profile_page',args[str(self.id)])


class StudentCategory(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name





class StudentDetails(models.Model):
    student = models.ForeignKey(StudentsProfile, on_delete=models.CASCADE)
    klass = models.ForeignKey(Klass, on_delete=models.CASCADE)
    division = models.ForeignKey(Division, on_delete=models.CASCADE)


class StudentAttendance(models.Model):
    student = models.ForeignKey(StudentDetails, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    academic_year = models.ForeignKey('users.SessionCalendar',on_delete=models.CASCADE)
    timetable = models.CharField(max_length=32)
    session_choice = (("1","Present"),
                      ("0","Absent"))
    session1 = models.CharField(max_length=1, choices=session_choice)
    session2 = models.CharField(max_length=1, choices=session_choice)



    # The value in this field is derived from the first two.
    # Updated every time the model instance is saved.
    daily_attendance = models.PositiveIntegerField(
        default=0,  # This value will be overwritten during save()
        editable=False,  # Hides this field in the admin interface.
    )

    def save(self, *args, **kwargs):
        # calculate sum before saving.
        self.daily_attendance = self.calculate_sum()
        super(StudentAttendance, self).save(*args, **kwargs)

    def calculate_sum(self):
        """ Calculate a numeric value for the model instance. """
        try:
            return (int(self.session1) + int(self.session2))
        except KeyError:
            # Value_a or value_b is not in the VALUES dictionary.
            # Do something to handle this exception.
            # Just returning the value 0 will avoid crashes, but could
            # also hide some underlying problem with your data.
            return 0

Edumia_v2/students/forms.py
from django import forms
from .models import StudentsProfile, StudentCategory
from klass.models import Klass,Division


class studentprofileform(forms.ModelForm):

    class Meta:
        model = StudentsProfile
        fields = ['admission_number', 'admission_date', 'klass', 'division',
                  'first_name', 'last_name',
                  'birthday', 'gender',
                  'birth_place', 'nationality',
                  'mothertounge', 'category',
                  'religion', 'caste', 'caste_category',
                  'address_line1', 'address_line2',
                  'city', 'state',
                  'pin_code', 'country',
                  'father_name', 'phone_number',
                  'mother_name', 'mother_phone_number',
                  'aadhaar_Number', 'email',
                  'height', 'weight', 'blood_group',
                  'vaccination_details','user']

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['division'].queryset = Division.objects.none()

Edumia_v2/students/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from students.models import StudentsProfile,Division,StudentCategory
from django.http import HttpResponse
from django.shortcuts import redirect
from .forms import studentprofileform
from klass.forms import KlassDivisionForm
from django.views.generic import CreateView,View
from django.urls import reverse_lazy
import requests
from rest_framework.authtoken.models import Token
from Edumia_v2.settings import URL
from api.serializers import StudentsProfileSerializer
# Create your views here.
def pending(request):
    pending_students=all_students(request)
    return render(request, 'students/students_profile.html', {'sp': pending_students})

def status_approvel(request):
    if request.method == 'GET':
        student_id = request.GET.get('id')
        student = StudentsProfile.objects.get(id=student_id)
        student.status = '1'
        student.save()
        pending_students = StudentsProfile.objects.all()
        return render(request, 'students/students_profile.html', {'sp': pending_students})

def status_denial(request):
    student_id = request.GET.get('id')
    student = StudentsProfile.objects.get(id=student_id)
    student.status = '2'
    student.save()
    pending_students = StudentsProfile.objects.all()
    return render(request, 'students/students_profile.html', {'sp': pending_students})

@login_required
def studentdashboard(request):
    token, created = Token.objects.get_or_create(user=request.user)
    return render(request,'students/students_dashboard.html',{'token':token})

# class AddStudent(CreateView):
#     model = StudentsProfile
#     form_class = studentprofileform
#     success_url = reverse_lazy('success')
def success(request):
    return HttpResponse('student added successfully')

def AddStudent(request):
    form = studentprofileform
    return render(request,'students/studentsprofile_form.html',{'form':form})
def get_divisions(request):
    klass_id = request.GET.get('klass')
    divisions = Division.objects.filter(klass_id=klass_id).order_by('name')
    return render(request, 'students/drop_down_divisions.html', {'divisions': divisions})

def all_students(request):
    token,created = Token.objects.get_or_create(user=request.user)
    header = {'Authorization':f'Token {token}'}
    response = requests.get((URL+'api/v1/studentsprofile/'),headers=header)
    students = response.json()
    return render(request,'students/allstudents.html',{'data':students})
    #return students


def profile(request):
    token, created = Token.objects.get_or_create(user=request.user)
    header = {'Authorization': f'Token {token}'}
    response = requests.get((URL + 'api/v1/studentsprofile/'), headers=header)
    students = response.json()
    return render(request, 'students/profile.html', {'data': students})

def get_profile(request):
    token, created = Token.objects.get_or_create(user=request.user)
    header = {'Authorization': f'Token {token}'}
    response = requests.get((URL + 'api/v1/studentsprofile/'), headers=header)
    students = response.json()
    return render(request, 'students/profile.html', {'data': students})

def student_phone_numbers(request):
    "page to select class and division to get contact number"
    form = KlassDivisionForm
    return render(request, 'students/student_phone_numbers.html', {'form': form})
def contact_numbers(request):
    "redirected from student_phone_numbers page with class and division filtered contact number list"
    klass = request.GET.get('klass')
    division = request.GET.get('division')
    token, created = Token.objects.get_or_create(user=request.user)
    header = {'Authorization': f'Token {token}'}
    api_end = 'api/v1/klass_students?'
    url="{URL}{api_end}klass={klass}&division={div}".format(URL=URL,api_end=api_end,klass=klass,div=division)
    response = requests.get(url, headers=header)
    students = response.json()
    return render(request, 'students/student_phone_numbers.html', {'data': students})

def student_info(request):
    "get all info from all students of a class-division page to select class and division to get contact number"
    form = KlassDivisionForm
    return render(request, 'students/student_info.html', {'form': form})

Edumia_v2/students/templates/students/allstudents.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All students</title>
</head>
<body>
<table>
<tr>
    <th>Firstname</th>
    <th>Lastname</th>
</tr>

<tr>
    {% for i in data %}
        {% if i.status == '1' %}

        <td><a href="{{ i.url }}"> {{ i.first_name }}</a></td>
        <td>{{ i.second_name }}</td>
</tr>
        {% endif %}
    {% endfor %}
</table>

<p>Test</p>
</body>
</html>

Edumia_v2/students/templates/students/drop_down_divisions.html
<option value="">---------</option>
{% for division in divisions %}
<option value="{{ division.pk }}">{{ division.name }}</option>
{% endfor %}

Edumia_v2/students/templates/students/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ data }}
</body>
</html>

Edumia_v2/students/templates/students/student_info (copy).html
{% extends 'base.html' %}

{% block content %}
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
  <script type="text/javascript">
    $(document).ready(function(){
        $("#btn").click(function(){
        $.ajax({
            type: 'GET',
            url: "http://127.0.0.1:8000/api/student_list/",
            success:function(data){
             alert(data);
            }
        });
    return false;
    });
});
</script>
</head>

<form id="KlassDivisionForm" method="get"  data-cities-url="{% url 'ajax_get_divisions' %}" novalidate>

    <table>
      {{ form.as_table }}
    </table>
    {% if not data %}
    <button id="contactbutton" type="submit">Get info</button>
    {% endif %}
  </form>
<button id="btn">Send an HTTP GET request to a page and get the result back</button>
<div>
    {% if data %}
   <table>
        <thead>
        <th>Name</th>
        <th>Admission No</th>
        <th>Phone</th>
        <th>Address</th>
        </thead>
        <tbody>{% for item in data %}
        <tr><td>{{ item.first_name}}</td>
            <td>{{ item.admission_number }}</td>
            <td>{{ item.phone_number }}</td>
            <td>{{ item.address_line1}}<br> {{ item.address_line2 }}</td>
         {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_klass").change(function () {
      var url = $("#KlassDivisionForm").attr("data-cities-url");  // get the url of the `load_cities` view
      var klassId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'klass': klassId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_division").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>


{% endblock %}

Edumia_v2/students/templates/students/student_info.html
{% extends 'base.html' %}

{% block content %}
<head>
 <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function(){
            $("select#id_klass").change(function(){
            var klass = $(this).children("option:selected").val();
            $("select#id_division").change(function(){
            var division = $(this).children("option:selected").val();


        $("#submit").click(function(){
        $.ajax({
            type: 'GET',
            url: ("http://127.0.0.1:8000/api/v1/klass_students?klass="+klass+"&division="+division),
            headers: { "Authorization" : "Token a96cead65bc330ddbde89cd1c8524e8721661660" },
            success:function(data){
            var i;
            var studentname="";
            for (i=0;i<data.length;i++){
            studentname +=  data[i].first_name+" "+data[i].last_name+"<br>";
            var student = studentname.link(data[i].url)
            }
             document.getElementById("studentsdata").innerHTML = student;
            }
        });
    return false;
    });
     });
});
});
</script>
</head>

<form id="KlassDivisionForm" method="get" data-cities-url="{% url 'ajax_get_divisions' %}" novalidate>

    <table>
      {{ form.as_table }}
    </table>
<!--    <button id="contactbutton" type="submit">Get info</button>-->
    <button id="submit">Get info</button>
  </form>

<div>
    <p id="studentsdata"></p>
</div>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_klass").change(function () {
      var url = $("#KlassDivisionForm").attr("data-cities-url");  // get the url of the `load_cities` view
      var klassId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'klass': klassId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_division").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

{% endblock %}

Edumia_v2/students/templates/students/student_phone_numbers.html
{% extends 'base.html' %}

{% block content %}

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<form id="KlassDivisionForm" method="get"  data-cities-url="{% url 'ajax_get_divisions' %}" novalidate>

    <table>
      {{ form.as_table }}
    </table>
    {% if not data %}
    <button id="contactbutton" type="submit">Get Contact Numbers</button>
    {% endif %}
  </form>
<script type="text/javascript">
    $(document).ready(function(){
            $("select#id_klass").change(function(){
            var klass = $(this).children("option:selected").val();
            $("select#id_division").change(function(){
            var division = $(this).children("option:selected").val();


        $("#contactbutton").click(function(){
        $.ajax({
            type: 'GET',
            url: ("http://127.0.0.1:8000/api/v1/klass_students?klass="+klass+"&division="+division),
            headers: { "Authorization" : "Token a96cead65bc330ddbde89cd1c8524e8721661660" },
            success:function(data){
            var i;
            var studentname="";
            for (i=0;i<data.length;i++){
            studentname +=  data[i].first_name+" "+data[i].last_name+"\t"+data[i].phone_number +"<br>";
            var student = studentname.link(data[i].url)
            }
             document.getElementById("studentsdata").innerHTML = student;
            }
        });
    return false;
    });
     });
});
});
</script>
<div>

        <p id="studentsdata"></p>
</div>


  <script>
    $("#id_klass").change(function () {
      var url = $("#KlassDivisionForm").attr("data-cities-url");  // get the url of the `load_cities` view
      var klassId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'klass': klassId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_division").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>


{% endblock %}

Edumia_v2/students/templates/students/students_dashboard.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.number }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a> |
  <a href="{% url 'signup' %}">signup</a>
{% endif %}
  <h3>Students</h3>
  <form>
    <input type="text" name="search" placeholder="" value="">
    <button>Search</button>
  </form>
  <button><a href="{% url 'all_students' %}"> All Students</a></button>
  <button><a href="add-student"> Admit Student</a></button>
  <button><a href="{% url 'student_phone_numbers' %}">Contact Numbers  </a> </button>
  <button><a href="{% url 'student_info' %}">Student Info  </a> </button>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript">
  $(document).ready(function(){
  localStorage.setItem("token", "{{ token }}");

  });
</script>
{% endblock %}

Edumia_v2/students/templates/students/students_profile.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table>
<tr>
    <th>Firstname</th>
    <th>Lastname</th>
     <th>Approve</th>
     <th>Deny</th>
</tr>

<tr>
    {% for i in sp %}
        {% if i.status == '0' %}

        <td>{{ i.first_name }}</td>
        <td>{{ i.second_name }}</td>
        <td><button type="button"> <a href="{% url 'approvel' %}?id={{i.id}}" >Approve</a></button></td>
        <td><button type="button"><a href="{% url 'denial' %}?id={{i.id}}" >Deny</a></button></td>
    </tr>
        {% endif %}
    {% endfor %}
</table>

</body>
</html>

Edumia_v2/students/templates/students/studentsprofile_form.html
<h2>Person Form</h2>

  <form method="post" action="http://127.0.0.1:8000/api/student_list/" id="studentprofileform" data-cities-url="{% url 'ajax_get_divisions' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_klass").change(function () {
      var url = $("#studentprofileform").attr("data-cities-url");  // get the url of the `load_cities` view
      var klassId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'klass': klassId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_division").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>